/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-06 PL9 A33 Prime 12um zhead -16kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 A15 Prime Move zhead -5kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 B19 21nmRLT 15.2um Zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 DFI28 PRIME 16.3um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB05 Prime 12um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB09 12um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB22 12um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 PL9 PRIME ZA06 16p3um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 ZA24 DFI28 PRIME 16.3um zhead -20kPa.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 C48N -20kPa Replica 35kPa thin RLT.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 ZA29 -20kPa Replica 40kPa Master Prime.mp4'
/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -i '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 ZB14 -20kPa replica 35kPa master.mp4'
