#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-06 PL9 A33 Prime 12um zhead -16kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 A15 Prime Move zhead -5kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 B19 21nmRLT 15.2um Zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 DFI28 PRIME 16.3um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB05 Prime 12um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB09 12um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB22 12um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 PL9 PRIME ZA06 16p3um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 ZA24 DFI28 PRIME 16.3um zhead -20kPa.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 C48N -20kPa Replica 35kPa thin RLT.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 ZA29 -20kPa Replica 40kPa Master Prime.mp4'
#/home/trafferty/data/scripts/ContactFront_MR_HoughCircles.py --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 ZB14 -20kPa replica 35kPa master.mp4'

#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-03 ZA06 -20kPa 60sec ramp 20nmRLT (nice_LPCUpRt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-03 ZA24 -20kPa 60sec ramp 21nmRLT (stallsThenVeryAbrupt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-03 ZB14 -20kPa 60sec ramp 20nmRLT (stallsThenAbrupt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-04 DFI28 B47 -16kPa 60 sec ramp up  15.2 um zhead 21nmRLT (nice_LPCCenteredUpRt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-04 DFI28 C42N -16kPa 60 sec ramp up  16.3 um zhead 21nmRLT (noSep)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-04 DFI28 C48N DNP POR 21nmRLT (nice_LPCCentered)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-06 DFI28 A15 Prime 16.3um zhead -16kPa (slowToSeparateFromLt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-06 PL9 A33 Prime 12um zhead -16kPa (noSeparation)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 A15 Prime Move zhead -5kPa (nice_LPCNearCenterUpRt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-07 DFI28 B19 21nmRLT 15.2um Zhead -20kPa (overExposed)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB05 Prime 12um zhead -20kPa (badSeparation)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-10 PL9 ZB09 12um zhead -20kPa (nice_LPCToRt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 PL9 PRIME ZA06 16p3um zhead -20kPa (niceSeparation)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-11 ZA24 DFI28 PRIME 16.3um zhead -20kPa (niceSeparation)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 C48N -20kPa Replica 35kPa thin RLT (LPClowerRt)_trimmed.mp4'
#~ /home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/2015-08-20 DFI28 ZA29 -20kPa Replica 40kPa Master Prime (abruptSeparation)_trimmed.mp4'

/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm_HX1-223_prime1_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-HX1-223-Prime2_trimmed.mp4' 
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-J62-507-Prime1_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-J92-618-Prime1_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-J92-627-Prime2_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-J92-628-Prime1_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-K80-250-S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm_K80-253-S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm_K80-254_S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-K80-256-S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-K81-261-S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI20-50nm-K81-284-S_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-I52-038-S-wmv_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-I72-133_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J52-426-S 15um_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J52-431-Prime_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J52-432-S-wmv_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J52-438_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J52-438-Prime_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J90-585_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J92-624-S-wmv_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/DFI28-J92-627-S 14um_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/PL9_J52-432_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/T32G-J61-456-Prime2_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/T32G-J72-535-Prime1_trimmed.mp4'
/home/trafferty/data/scripts/ContactFront_MR.py -s EdgeCircle --no-plot -v -f '/home/trafferty/tmp/no_backup/MR_Spreadcam/DNP/T32G-J92-617-S_trimmed.mp4'
